# Generated by Django 4.0.2 on 2022-02-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_organization_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
